{% set name = "openff-toolkit" %}
{% set version = "0.19.0" %}
{% set python_min = '3.12' %}

package:
  name: openff-toolkit-split
  version: {{ version }}

source:
  git_url: https://github.com/openforcefield/{{ name }}.git
  git_rev: {{ version }}
  git_depth: -1

build:
  number: 1

outputs:
  - name: openff-toolkit-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }},<3.15.0a0 
        - packaging
        - numpy
        - openff-forcefields
        - openff-amber-ff-ports >=2025.09.0
        - openff-units >=0.2
        - openff-utilities
        - rdkit !=2024.03.6
        - networkx >=2.5
        - xmltodict
        - bson
        - python-constraint
        - cachetools
      run_constrained:
        - openforcefield ==9999999999
        - pydantic <3.0.0a0
        - qcportal >=0.50.0

    test:
      requires:
        - python {{ python_min }}
      imports:
        - openff.toolkit
        - rdkit

  - name: openff-toolkit
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - openmm >=8
        - openff-interchange >=0.5
        - {{ pin_subpackage('openff-toolkit-base', exact=True) }}
        - openff-nagl >=0.5.2
        - openff-nagl-models >=2025
      run_constrained:
        - ambertools >=22

    test:
      requires:
        - python {{ python_min }}
        - qcportal
      imports:
        - openff.toolkit
      files:
        - test_openff_toolkit.py
      commands:
        - python test_openff_toolkit.py

  - name: openff-toolkit-examples
    script: move-examples.sh
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - jupyterlab
        - nglview
        - mdtraj
        - qcelemental
        - qcportal >=0.50.0
        - qcengine
        - pdbfixer
        - {{ pin_subpackage('openff-toolkit', exact=True) }}

    test:
      requires:
        - python {{ python_min }}
      files:
        - test_examples_copied.py
      source_files:
        - examples
      commands:
        - python test_examples_copied.py

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modern, extensible library for molecular mechanics force field science from the Open Force Field Initiative
  description: |
    The Open Force Field Toolkit, built by the Open Force Field Initiative, is a Python
    toolkit for the development and application of modern molecular mechanics force fields
    based on direct chemical perception and rigorous statistical parameterization methods.
  doc_url: https://docs.openforcefield.org/projects/toolkit/en/stable/
  dev_url: https://github.com/openforcefield/openff-toolkit

extra:
  recipe-maintainers:
    - jaimergp
    - j-wags
    - mattwthompson
